
import React, { useState, useRef, useCallback } from 'react';

interface ShaderNode {
    id: string;
    type: 'input' | 'math' | 'color' | 'output' | 'texture' | 'time';
    label: string;
    position: { x: number; y: number };
    inputs: string[];
    outputs: string[];
    value?: any;
}

interface ShaderEdge {
    id: string;
    from: string;
    fromOutput: string;
    to: string;
    toInput: string;
}

interface ShaderGraphProps {
    onCompile?: (glsl: string) => void;
    onApplyToObjects?: (materialId: string) => void;
}

const NODE_TEMPLATES: Record<string, Omit<ShaderNode, 'id' | 'position'>> = {
    color: { type: 'color', label: 'Color', inputs: [], outputs: ['rgb'], value: '#438ab5' },
    time: { type: 'time', label: 'Time', inputs: [], outputs: ['value'] },
    multiply: { type: 'math', label: 'Multiply', inputs: ['a', 'b'], outputs: ['result'] },
    add: { type: 'math', label: 'Add', inputs: ['a', 'b'], outputs: ['result'] },
    sin: { type: 'math', label: 'Sin', inputs: ['x'], outputs: ['result'] },
    output: { type: 'output', label: 'Fragment Output', inputs: ['color', 'alpha'], outputs: [] },
    texture: { type: 'texture', label: 'Texture Sample', inputs: ['uv'], outputs: ['rgb', 'a'] },
};

export const ShaderGraph: React.FC<ShaderGraphProps> = ({ onCompile, onApplyToObjects }) => {
    const [nodes, setNodes] = useState<ShaderNode[]>([
        { id: 'n1', type: 'color', label: 'Base Color', position: { x: 50, y: 100 }, inputs: [], outputs: ['rgb'], value: '#438ab5' },
        { id: 'n2', type: 'output', label: 'Fragment Output', position: { x: 400, y: 150 }, inputs: ['color', 'alpha'], outputs: [] },
    ]);
    const [edges] = useState<ShaderEdge[]>([]); // Future: implement edges
    const [selectedNode, setSelectedNode] = useState<string | null>(null);
    const [draggingNode, setDraggingNode] = useState<string | null>(null);
    const [dragOffset, setDragOffset] = useState({ x: 0, y: 0 });
    const canvasRef = useRef<HTMLDivElement>(null);

    const handleMouseDown = (nodeId: string, e: React.MouseEvent) => {
        const node = nodes.find(n => n.id === nodeId);
        if (node) {
            setDraggingNode(nodeId);
            setDragOffset({ x: e.clientX - node.position.x, y: e.clientY - node.position.y });
            setSelectedNode(nodeId);
        }
    };

    const handleMouseMove = useCallback((e: React.MouseEvent) => {
        if (draggingNode) {
            setNodes(prev => prev.map(n =>
                n.id === draggingNode
                    ? { ...n, position: { x: e.clientX - dragOffset.x, y: e.clientY - dragOffset.y } }
                    : n
            ));
        }
    }, [draggingNode, dragOffset]);

    const handleMouseUp = () => {
        setDraggingNode(null);
    };

    const addNode = (type: string) => {
        const template = NODE_TEMPLATES[type];
        if (template) {
            const newNode: ShaderNode = {
                ...template,
                id: `n${Date.now()}`,
                position: { x: 200, y: 200 }
            };
            setNodes(prev => [...prev, newNode]);
        }
    };

    const compileToGLSL = () => {
        const glsl = `
// Generated by POG-Ultimate Shader Graph
precision mediump float;

uniform float u_time;
uniform vec3 u_baseColor;

void main() {
  vec3 color = u_baseColor;
  float pulse = sin(u_time * 2.0) * 0.5 + 0.5;
  gl_FragColor = vec4(color * pulse, 1.0);
}
    `.trim();
        onCompile?.(glsl);
    };

    return (
        <div className="h-full flex flex-col bg-[#232323] text-[#aaa] font-sans overflow-hidden">
            {/* Toolbar */}
            <div className="h-14 bg-[#282e2e] border-b border-[#394443] px-6 flex items-center justify-between shrink-0">
                <div className="flex items-center space-x-4">
                    <span className="text-[10px] font-black uppercase tracking-widest text-[#438ab5]">Shader Graph Builder</span>
                    <div className="w-px h-6 bg-[#394443]"></div>
                    <div className="flex space-x-2">
                        {Object.keys(NODE_TEMPLATES).map(type => (
                            <button
                                key={type}
                                onClick={() => addNode(type)}
                                className="px-3 py-1.5 bg-[#232323] border border-[#394443] rounded-lg text-[9px] font-black uppercase text-[#438ab5] hover:bg-[#394443] transition-all"
                            >
                                + {type}
                            </button>
                        ))}
                    </div>
                </div>
                <div className="flex items-center space-x-4">
                    <button
                        onClick={compileToGLSL}
                        className="px-6 py-2 bg-[#438ab5] hover:bg-[#3e5b6d] text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all shadow-lg shadow-[#438ab5]/20"
                    >
                        Generate GLSL
                    </button>
                    <button
                        onClick={() => onApplyToObjects?.('default')}
                        className="px-6 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all"
                    >
                        Apply to Target
                    </button>
                </div>
            </div>

            {/* Canvas */}
            <div
                ref={canvasRef}
                className="flex-1 relative overflow-hidden bg-[#232323]"
                onMouseMove={handleMouseMove}
                onMouseUp={handleMouseUp}
                onMouseLeave={handleMouseUp}
                style={{
                    backgroundImage: 'radial-gradient(circle, #2a3434 1px, transparent 1px)',
                    backgroundSize: '20px 20px'
                }}
            >
                {/* Nodes */}
                {nodes.map(node => (
                    <div
                        key={node.id}
                        onMouseDown={(e) => handleMouseDown(node.id, e)}
                        className={`absolute w-40 bg-[#282e2e]/95 border rounded-2xl shadow-2xl backdrop-blur-xl cursor-move transition-all ${selectedNode === node.id ? 'border-[#438ab5] shadow-[0_0_30px_rgba(67,138,181,0.2)]' : 'border-[#394443]'
                            }`}
                        style={{ left: node.position.x, top: node.position.y }}
                    >
                        <div className={`px-4 py-2 border-b border-[#394443] rounded-t-2xl ${node.type === 'output' ? 'bg-emerald-600/10' : node.type === 'color' ? 'bg-purple-600/10' : 'bg-[#438ab5]/10'
                            }`}>
                            <span className="text-[9px] font-black uppercase text-[#8397a5] tracking-widest">{node.label}</span>
                        </div>
                        <div className="p-3 space-y-2">
                            {node.inputs.map(input => (
                                <div key={input} className="flex items-center space-x-2">
                                    <div className="w-1.5 h-1.5 rounded-full bg-amber-500 border border-amber-400"></div>
                                    <span className="text-[8px] text-slate-500 uppercase font-bold">{input}</span>
                                </div>
                            ))}
                            {node.type === 'color' && (
                                <input
                                    type="color"
                                    value={node.value || '#438ab5'}
                                    onChange={(e) => setNodes(prev => prev.map(n => n.id === node.id ? { ...n, value: e.target.value } : n))}
                                    className="w-full h-8 rounded-lg cursor-pointer bg-transparent border-none"
                                />
                            )}
                            {node.outputs.map(output => (
                                <div key={output} className="flex items-center justify-end space-x-2">
                                    <span className="text-[8px] text-slate-500 uppercase font-bold">{output}</span>
                                    <div className="w-1.5 h-1.5 rounded-full bg-cyan-500 border border-cyan-400"></div>
                                </div>
                            ))}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default ShaderGraph;
